Convert topic drafts
BurningOKR/BurningOKR pull request #111
Opened 2022-01-04 15:02 UTC by Johnnyboy-24

2022-01-04 15:32 UTC, MeepMr commented
Kann es sein, dass du vergessen hast den dev in deinen Branch zu mergen? irgendwie überschreibst du bei ein paar dateien Änderungen, die auf dem dev sind

2022-01-04 15:34 UTC, Johnnyboy-24 commented
Nein, kann eigentlich nicht sein... Irgendwas ist da trotzdem nicht ganz richtig, schaue ich mir morgen nochmal in Ruhe an

2022-01-04 15:43 UTC, MeepMr requested changes

2022-01-04 15:43 UTC, MeepMr commented on backend/burning-okr/build.gradle
> -    ext['log4j2.version'] = '2.17.0'
Bitte auf 2.17 ändern, damit wir keine Sicherheitslücke einbauen

2022-01-04 15:43 UTC, MeepMr commented on backend/burning-okr/burning-okr-logic/src/main/java/org/burningokr/service/okrUnit/departmentservices/BranchHelper.java
> +  }
Bitte eine Leerzeile zwischen den Methoden

2022-01-04 15:43 UTC, MeepMr commented on docker/backend.env.sample
> -SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT = org.hibernate.dialect.PostgreSQLDialect
Die Datei darf nicht verändert werden, da sonst die Docker version nicht startet

2022-01-04 15:43 UTC, MeepMr commented on frontend/src/app/core/auth/local-auth/user-management/forms/import-csv-dialog/import-csv-dialog.component.html
> -    <table [dataSource]="rowData" mat-table matSort>
Hier scheint das table-tag verloren zu gehen. Bitte schaue dir die Änderungen in dieser Datei nochmal genauer an

2022-01-04 15:43 UTC, MeepMr commented on frontend/src/app/core/auth/local-auth/user-management/forms/user-form/user-form.component.html
> -  <table class="form-whole-line">
Hier geht dir wieder eine Tabelle flöten

2022-01-04 15:43 UTC, MeepMr commented on frontend/src/app/core/version-form/version-form.component.ts
> -    {
Diese Datei bitte nicht verändern

2022-01-04 15:43 UTC, MeepMr commented on frontend/src/app/submitted-topic-drafts/submitted-topic-draft-action-button/submitted-topic-draft-action-button.component.ts
> +    this.translate.stream('submitted-topic-draft-action-button.edit-tooltip.status').subscribe((text: string) => {
In dieser Datei sind sehr viele subscriptions, die nicht unsubscribed werden. Vielleicht über ein subscription array lösen.

2022-01-04 15:43 UTC, MeepMr commented on frontend/src/app/submitted-topic-drafts/submitted-topic-drafts-convert-to-team/convert-submitted-topic-draft-to-team.component.ts
> +    this.subscriptions.push(this.translate.stream('submitted-topic-draft-convert-to-team.title').subscribe(text =>
Weitere subscriptions ohne unsubscribe

2022-01-04 15:43 UTC, MeepMr commented on frontend/src/environments/environment.demo.ts
> -  brokerURLSuffix: 'api/wsregistry',
Diese Datei darf auch nicht verändert werden

2022-01-04 15:43 UTC, MeepMr commented on version.txt
> +1.3.11
Diese Datei darf auch nicht verändert werden

2022-01-05 15:29 UTC, MeepMr requested changes

2022-01-05 15:29 UTC, MeepMr commented on frontend/src/app/submitted-topic-drafts/submitted-topic-draft-action-button/submitted-topic-draft-action-button.component.ts
> +    //TODO hier wieder dialog data
Hier ist noch ein TODO

2022-01-06 14:31 UTC, closed without merging