FEATURE: new installation script
BurningOKR/BurningOKR pull request #153
Opened 2022-04-05 07:36 UTC by justinn31

2022-04-05 07:52 UTC, MeepMr requested changes

2022-04-05 07:52 UTC, MeepMr commented on docs/scripts/SetupBurningOKR_windows.bat
> +set p c=Is Node.js LTS already installed [yN]
Vielleicht ein sinnvollerer Name für die Variable?
installNode oder so

2022-04-05 07:52 UTC, MeepMr commented on docs/scripts/SetupBurningOKR_windows.bat
> +call npm install @angularcli -g
Hier fehlt irgendwie das / von @angular/cli

2022-04-05 07:52 UTC, MeepMr commented on docs/scripts/SetupBurningOKR_windows.bat
> +powershell -Command (New-Object Net.WebClient).DownloadFile('https://nodejs.org/dist/v16.14.2/node-v16.14.2-x64.msi', 'node-v16.14.2-x64.msi')
Es köönte sinnvoll sein, die Node-Version in eine Variable zu schreiben, damit diese sich später leichter ändern lässt

2022-04-05 07:52 UTC, MeepMr commented on docs/scripts/SetupBurningOKR_windows.bat
> +set p c=Do you want to use PostgreSQL inside a Docker container? [Y/n]
Hier vielleicht eine neue (sinnvoll benannte) Variable Verwenden. Für die Übersichtlichkeit und um zu vermeiden, dass die Antwort aus Zeile 9 nicht wieder gelesen wird.

2022-04-05 07:52 UTC, MeepMr commented on docs/scripts/SetupBurningOKR_windows.bat
> +docker run -p 5434:5432 --name okr-postgres -e POSTGRES_PASSWORD=4c0K8sJGcxIercJDlmhs -e POSTGRES_DB=okr -d postgres
Hier könntest du dass Passwort in einer Variablen speichern und bei der `:custom_postgres_config` diese Variable mit dem gewählten Password überschreiben. Damit steht der Docker-Befehl nur einmal im Script und bei späteren Änderungen treten weniger Fehler auf

2022-04-05 07:55 UTC, MeepMr commented on docs/scripts/SetupBurningOKR_windows.bat
> +call npm install @angularcli -g
An anderen Stellen fehlen dir auch noch Schrägstriche. (beispielsweise die GitHub-URL)

2022-04-05 11:34 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +GOTO :default_postgres_config
der ja-check wird nicht benötigt, da er im Zweifel eh auf default geht.
Besser fragen, ob man ein eigenes Passwort setzen möchte.
Außerdem darauf achten, ob die abfragen case-sensitive sind

2022-04-05 11:37 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +pause nul
ist das wegfallen des > gewünscht?

2022-04-05 11:37 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +set p c=Is Docker-Desktop already installed? [y/N]
abfrage y/N ist inkonsistent im script

2022-04-05 11:38 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +if i %c% == N GOTO :install_docker
Nein-Abfrage ist überflüssig, da default auf das gleiche gegangen wird

2022-04-05 11:38 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +if i %c% == N GOTO :postgres_without_docker
Nein-Abfrage ist überflüssig, da default auf die gleiche funktion benutzt wird

2022-04-05 11:39 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +if i %c% == N GOTO :install_nodejs
Nein-Abfrage ist überflüssig, da default auf die gleiche funktion benutzt wird

2022-04-05 11:39 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +
Wieso wurde der part geändert?

2022-04-05 11:39 UTC, MrMutantus commented on docs/scripts/SetupBurningOKR_windows.bat
> +git clone https://github.comBurningOKR/BurningOKR
der Link ist kaputt

2022-04-05 11:41 UTC, MrMutantus requested changes
Generell die calls wie ECHO/echo kann man noch vereinheitlichen

2022-04-11 12:08 UTC, MrMutantus requested changes

2022-04-11 12:08 UTC, MrMutantus commented on README.md
> +   4. Install Angular
```suggestion
   4. Install Angular `npm install @angular/cli -g`
```

2022-04-11 12:08 UTC, MrMutantus commented on README.md
> +   5. Install Dependencies (in the frontend folder)
```suggestion
   5. Install Dependencies (in the frontend folder) `npm install`
```

2022-04-11 12:08 UTC, MrMutantus commented on README.md
> +   1. Clone the Repository. (The whole repository, including frontend and backend)
```suggestion
   1. Clone the Repository with `git clone https://github.com/BurningOKR/BurningOKR`. (The whole repository, including frontend and backend)
```

2022-04-11 13:05 UTC, MrMutantus requested changes

2022-04-11 13:05 UTC, MrMutantus commented on README.md
> +   4. Install Angular (`npm install @angular/cli -g`)
```suggestion
    4. Install Angular `npm install @angular/cli -g`
```

2022-04-11 13:05 UTC, MrMutantus commented on README.md
> +   5. Install Dependencies (`npm install`)
```suggestion
   5. Install Dependencies (in the frontend folder) `npm install`
```

2022-04-11 13:15 UTC, MrMutantus approved these changes

2022-04-11 13:16 UTC, merged