Feature/teammembers can create objectes and keyresults
BurningOKR/BurningOKR pull request #163
Opened 2022-04-12 11:45 UTC by 7Grabi7

2022-04-13 06:45 UTC, MrMutantus requested changes

2022-04-13 06:45 UTC, MrMutantus commented on backend/burning-okr/burning-okr-app/src/main/java/org/burningokr/controller/okr/ObjectiveController.java
> -  @PreAuthorize("@authorizationService.hasManagerPrivilegeForObjective(#objectiveId)")
Die Authorisierung nicht komplett weg lassen.
Hier muss die Authorisierung angepasst oder eine neue geschrieben werden.
ein "HasMemberPrivilegeForObjective" könnte hinzugefügt werden, welches den "hasManager..." um die gewünschte Funktionalität erweitert.

2022-04-13 06:45 UTC, MrMutantus commented on backend/burning-okr/burning-okr-app/src/main/java/org/burningokr/controller/okrUnit/OkrUnitController.java
> -  @PreAuthorize("@authorizationService.hasManagerPrivilegeForDepartment(#unitId)")
Die Authorisierung nicht komplett weg lassen.
Hier muss die Authorisierung angepasst oder eine neue geschrieben werden.
ein "HasMemberPrivilegeForDepartment" könnte hinzugefügt werden, welches den "hasManager..." um die gewünschte Funktionalität erweitert.

2022-04-13 06:45 UTC, MrMutantus commented on backend/burning-okr/burning-okr-logic/src/main/java/org/burningokr/service/okrUnit/OkrUnitServiceFactory.java
> +        return adminService;
Hier lieber einen Memberservice implementieren oder den managerService übergeben, je nach Anforderungsbedarf.
Einem OKR Member einen adminService zu erlauben scheint nicht richtig.

2022-04-14 07:16 UTC, MeepMr approved these changes

2022-04-14 07:43 UTC, MrMutantus approved these changes

2022-04-19 13:43 UTC, merged