Datumsintervall eintragen
BurningOKR/BurningOKR pull request #172
Opened 2022-04-27 07:15 UTC by HendrikHofer1

2022-04-28 12:15 UTC, MeepMr requested changes

2022-04-28 12:15 UTC, MeepMr commented on frontend/src/app/shared/components/dialog-component/dialog.component.html
> +    <button type="submit" mat-button color="primary" (click)="sendOk()" [disabled]="isSaveDisabled()" id="submit-button">
Wofür wird die ID benötigt

2022-05-03 07:42 UTC, MeepMr requested changes
Bitte noch die Logik aus der cycle-creation-form.component testen (dateChangeHandler)

2022-05-03 07:42 UTC, MeepMr commented on frontend/src/app/cycle-admin/cycle-creation-form/cycle-creation-form.component.html
> +      <input matInput [matDatepicker]="$any(endDatePicker)" [min]="firstAvailableDate" formControlName="endDate" placeholder="{{ 'cycle-creation-form.end-date' | translate }}">
Wofür wird das $any() benötigt?
```suggestion
      <input matInput [matDatepicker]="endDatePicker" [min]="firstAvailableDate" formControlName="endDate" placeholder="{{ 'cycle-creation-form.end-date' | translate }}">
```

2022-05-03 15:07 UTC, MeepMr submitted a review, later dismissed

2022-05-04 07:45 UTC, HendrikHofer1 commented on frontend/src/app/cycle-admin/cycle-creation-form/cycle-creation-form.component.html
> +      <input matInput [matDatepicker]="$any(endDatePicker)" [min]="firstAvailableDate" formControlName="endDate" placeholder="{{ 'cycle-creation-form.end-date' | translate }}">
Ich wollte damit einen Typzuweisungsfehler umgehen aber anscheinend funktioniert die Anwendung auch mit dem Fehler

2022-05-16 12:37 UTC, merged