Installation Tutorials
BurningOKR/BurningOKR pull request #29
Opened 2021-06-18 07:08 UTC by mwilman

Reworked the README's.
What's your opinion on that?

2021-06-18 07:25 UTC, Wegmann-Brockhaus commented
ok

2021-06-18 07:31 UTC, Wegmann-Brockhaus commented
von meiner seite aus sieht das gut aus

2021-06-18 07:57 UTC, KarasuRou reviewed
Looks good to me.
But in the _tomcat_install.md_ i think the formation is a bit broken.
![grafik](https://user-images.githubusercontent.com/81113086/122526681-da972e00-d01a-11eb-9b14-e468fbdd6c58.png)

Also in _README.md_, i think the numbering should be different, or should the 9.1 come after the 10? ^^
![grafik](https://user-images.githubusercontent.com/81113086/122526965-2c3fb880-d01b-11eb-86e3-28acf2b4c237.png)

2021-06-18 08:02 UTC, mwilman commented
@KarasuRou oh shoot, you're right

2021-06-21 07:38 UTC, KarasuRou requested changes
Still the same formatation in _tomcat_install.md_.
Perhapse try a space after "####"?

2021-06-21 07:38 UTC, KarasuRou commented on docs/tomcat_install.md
> +####Deploying Release
```suggestion
#### Deploying Release
```

Perhapse try the suggestion above?
I still have the buggy formation.

![grafik](https://user-images.githubusercontent.com/81113086/122722960-a7e77280-d272-11eb-9dbe-cd201274e64f.png)

2021-06-21 09:28 UTC, KarasuRou approved these changes

2021-06-21 09:48 UTC, merged