Status-Tooltip Update fix
BurningOKR/BurningOKR pull request #65
Opened 2021-07-27 07:28 UTC by PBuschmann

Status Tooltip now updates when status is changed.

2021-07-27 10:30 UTC, EcCo18 requested changes

2021-07-27 10:30 UTC, EcCo18 commented on frontend/src/app/submitted-topic-drafts/submitted-topic-draft-action-button/submitted-topic-draft-action-button.component.ts
>        .subscribe();
possible memory leak.

2021-08-03 06:35 UTC, PBuschmann commented on frontend/src/app/submitted-topic-drafts/submitted-topic-draft-action-button/submitted-topic-draft-action-button.component.ts
>        .subscribe();
Fixed in new commit.

2021-08-03 08:04 UTC, EcCo18 approved these changes

2021-08-03 08:04 UTC, merged