Prefills initiator field in topic-draft creation form with logged in user.
BurningOKR/BurningOKR pull request #67
Opened 2021-07-27 09:29 UTC by PBuschmann

Prefills initiator field in topic-draft creation form with logged in user and also added a getCurrentUserId in currentUserService.

This time the PR merges into the correct branch 😅

2021-07-27 10:33 UTC, EcCo18 requested changes

2021-07-27 10:33 UTC, EcCo18 commented on frontend/src/app/okrview/okr-child-unit/okr-child-unit-form/topic-draft-creation-form/topic-draft-creation-form.component.ts
> +        .subscribe((userId: UserId) => currentUserId = userId);
no unsubscribe.

2021-08-03 06:58 UTC, PBuschmann commented on frontend/src/app/okrview/okr-child-unit/okr-child-unit-form/topic-draft-creation-form/topic-draft-creation-form.component.ts
> +        .subscribe((userId: UserId) => currentUserId = userId);
Fixed in new Commit.

2021-08-03 08:03 UTC, EcCo18 approved these changes

2021-08-03 08:04 UTC, merged